# -*- coding: utf-8 -*-
"""question_answer_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ihH7jUQYCa26VxQKCxFktaCbo_zV_-lH
"""

!pip install langchain-huggingface
!pip install huggingface_hub
!pip install transformers
!pip install accelerate
!pip install bitsandbytes
!pip install langchain

!pip install streamlit datasets rapidfuzz

#environment secret key
from google.colab import userdata
sec_key=userdata.get('HF_TOKEN')
print(sec_key)

from langchain_huggingface import HuggingFaceEndpoint

#environment secret key
from google.colab import userdata
sec_key=userdata.get('HUGGING_FACE')
print(sec_key)

#importing the key in the environment
import os
os.environ['HUGGING_FACE']=sec_key

pip install datasets

from transformers import pipeline
import pandas as pd

from datasets import load_dataset
dataset = load_dataset("MakTek/Customer_support_faqs_dataset")

for item in dataset['train']:
    print(item['question'], item['answer'])

"""Here is your **question-answer dataset in a clean table format** (Markdown), based on the content from your file[1]:

| Question | Answer |
|----------|--------|
| How can I create an account? | To create an account, click on the 'Sign Up' button on the top right corner of our website and follow the instructions to complete the registration process. |
| What payment methods do you accept? | We accept major credit cards, debit cards, and PayPal as payment methods for online orders. |
| How can I track my order? | You can track your order by logging into your account and navigating to the 'Order History' section. There, you will find the tracking information for your shipment. |
| What is your return policy? | Our return policy allows you to return products within 30 days of purchase for a full refund, provided they are in their original condition and packaging. Please refer to our Returns page for detailed instructions. |
| Can I cancel my order? | You can cancel your order if it has not been shipped yet. Please contact our customer support team with your order details, and we will assist you with the cancellation process. |
| How long does shipping take? | Shipping times vary depending on the destination and the shipping method chosen. Standard shipping usually takes 3-5 business days, while express shipping can take 1-2 business days. |
| Do you offer international shipping? | Yes, we offer international shipping to select countries. The availability and shipping costs will be calculated during the checkout process based on your location. |
| What should I do if my package is lost or damaged? | If your package is lost or damaged during transit, please contact our customer support team immediately. We will initiate an investigation and take the necessary steps to resolve the issue. |
| Can I change my shipping address after placing an order? | If you need to change your shipping address, please contact our customer support team as soon as possible. We will do our best to update the address if the order has not been shipped yet. |
| How can I contact customer support? | You can contact our customer support team by phone at [phone number] or by email at [email address]. Our team is available [working hours] to assist you with any inquiries or issues you may have. |
| Do you offer gift wrapping services? | Yes, we offer gift wrapping services for an additional fee. During the checkout process, you can select the option to add gift wrapping to your order. |
| What is your price matching policy? | We have a price matching policy where we will match the price of an identical product found on a competitor's website. Please contact our customer support team with the details of the product and the competitor's offer. |
| Can I order by phone? | Unfortunately, we do not accept orders over the phone. Please place your order through our website for a smooth and secure transaction. |
| Are my personal and payment details secure? | Yes, we take the security of your personal and payment details seriously. We use industry-standard encryption and follow strict security protocols to ensure your information is protected. |
| What is your price adjustment policy? | If a product you purchased goes on sale within 7 days of your purchase, we offer a one-time price adjustment. Please contact our customer support team with your order details to request the adjustment. |
| Do you have a loyalty program? | Yes, we have a loyalty program where you can earn points for every purchase. These points can be redeemed for discounts on future orders. Please visit our website to learn more and join the program. |
| Can I order without creating an account? | Yes, you can place an order as a guest without creating an account. However, creating an account offers benefits such as order tracking and easier future purchases. |
| Do you offer bulk or wholesale discounts? | Yes, we offer bulk or wholesale discounts for certain products. Please contact our customer support team or visit our Wholesale page for more information and to discuss your specific requirements. |
| Can I change or cancel an item in my order? | If you need to change or cancel an item in your order, please contact our customer support team as soon as possible. We will assist you with the necessary steps. |
| How can I leave a product review? | To leave a product review, navigate to the product page on our website and click on the 'Write a Review' button. You can share your feedback and rating based on your experience with the product. |

*This table shows the first 20 Q&A pairs for readability. If you need the complete table or a downloadable file, let me know!*[1]


"""



def get_answer(user_question):
    for item in dataset['train']:
        if user_question.lower() in item['question'].lower():
            return item['answer']
    return "Sorry, I couldn't find an answer to your question."

# Example usage:
user_q = "How can I reset my password?"
print(get_answer(user_q))

pip install thefuzz

pip install python-Levenshtein

"""from table"""

from rapidfuzz import fuzz

def get_best_answer(user_question, threshold=60):
    best_score = 0
    best_answer = "Sorry, I couldn't find an answer to your question."
    for item in dataset['train']:
        score = fuzz.partial_ratio(user_question.lower(), item['question'].lower())
        if score > best_score and score >= threshold:
            best_score = score
            best_answer = item['answer']
    return best_answer

# Example usage:
user_q = "what is the rating?"
print(get_best_answer(user_q))

"""Here is your **question-answer dataset in a clean table format** (Markdown), based on the content from your file[1]:

| Question | Answer |
|----------|--------|
| How can I create an account? | To create an account, click on the 'Sign Up' button on the top right corner of our website and follow the instructions to complete the registration process. |
| What payment methods do you accept? | We accept major credit cards, debit cards, and PayPal as payment methods for online orders. |
| How can I track my order? | You can track your order by logging into your account and navigating to the 'Order History' section. There, you will find the tracking information for your shipment. |
| What is your return policy? | Our return policy allows you to return products within 30 days of purchase for a full refund, provided they are in their original condition and packaging. Please refer to our Returns page for detailed instructions. |
| Can I cancel my order? | You can cancel your order if it has not been shipped yet. Please contact our customer support team with your order details, and we will assist you with the cancellation process. |
| How long does shipping take? | Shipping times vary depending on the destination and the shipping method chosen. Standard shipping usually takes 3-5 business days, while express shipping can take 1-2 business days. |
| Do you offer international shipping? | Yes, we offer international shipping to select countries. The availability and shipping costs will be calculated during the checkout process based on your location. |
| What should I do if my package is lost or damaged? | If your package is lost or damaged during transit, please contact our customer support team immediately. We will initiate an investigation and take the necessary steps to resolve the issue. |
| Can I change my shipping address after placing an order? | If you need to change your shipping address, please contact our customer support team as soon as possible. We will do our best to update the address if the order has not been shipped yet. |
| How can I contact customer support? | You can contact our customer support team by phone at [phone number] or by email at [email address]. Our team is available [working hours] to assist you with any inquiries or issues you may have. |
| Do you offer gift wrapping services? | Yes, we offer gift wrapping services for an additional fee. During the checkout process, you can select the option to add gift wrapping to your order. |
| What is your price matching policy? | We have a price matching policy where we will match the price of an identical product found on a competitor's website. Please contact our customer support team with the details of the product and the competitor's offer. |
| Can I order by phone? | Unfortunately, we do not accept orders over the phone. Please place your order through our website for a smooth and secure transaction. |
| Are my personal and payment details secure? | Yes, we take the security of your personal and payment details seriously. We use industry-standard encryption and follow strict security protocols to ensure your information is protected. |
| What is your price adjustment policy? | If a product you purchased goes on sale within 7 days of your purchase, we offer a one-time price adjustment. Please contact our customer support team with your order details to request the adjustment. |
| Do you have a loyalty program? | Yes, we have a loyalty program where you can earn points for every purchase. These points can be redeemed for discounts on future orders. Please visit our website to learn more and join the program. |
| Can I order without creating an account? | Yes, you can place an order as a guest without creating an account. However, creating an account offers benefits such as order tracking and easier future purchases. |
| Do you offer bulk or wholesale discounts? | Yes, we offer bulk or wholesale discounts for certain products. Please contact our customer support team or visit our Wholesale page for more information and to discuss your specific requirements. |
| Can I change or cancel an item in my order? | If you need to change or cancel an item in your order, please contact our customer support team as soon as possible. We will assist you with the necessary steps. |
| How can I leave a product review? | To leave a product review, navigate to the product page on our website and click on the 'Write a Review' button. You can share your feedback and rating based on your experience with the product. |

*This table shows the first 20 Q&A pairs for readability. If you need the complete table or a downloadable file, let me know!*[1]



"""

from rapidfuzz import fuzz

# Assuming you've already loaded the dataset (e.g. via Hugging Face datasets)
# dataset = load_dataset("MakTek/Customer_support_faqs_dataset")

def get_best_answer(user_question, threshold=60):
    best_score = 0
    best_answer = "Sorry, I couldn't find an answer to your question."
    for item in dataset['train']:
        score = fuzz.partial_ratio(user_question.lower(), item['question'].lower())
        if score > best_score and score >= threshold:
            best_score = score
            best_answer = item['answer']
    return best_answer

# Interactive Q&A loop
print("Customer Support Bot: Ask me anything! Type 'exit' to quit.\n")
while True:
    user_q = input("You: ")
    if user_q.lower() == "exit":
        print("Bot: Goodbye! 👋")
        break
    answer = get_best_answer(user_q)
    print(f"Bot: {answer}\n")

# Install necessary packages if running locally
# !pip install streamlit datasets rapidfuzz

import streamlit as st
from datasets import load_dataset
from rapidfuzz import fuzz

# Load the FAQ dataset from Hugging Face
@st.cache_resource
def load_faq_dataset():
    dataset = load_dataset("MakTek/Customer_support_faqs_dataset")
    return dataset["train"]

dataset = load_faq_dataset()

# Function to get the best answer using fuzzy matching
def get_best_answer(user_question, threshold=60):
    best_score = 0
    best_answer = "❌ Sorry, I couldn't find an answer to your question."
    for item in dataset:
        score = fuzz.partial_ratio(user_question.lower(), item['question'].lower())
        if score > best_score and score >= threshold:
            best_score = score
            best_answer = item['answer']
    return best_answer

# Streamlit UI
st.title("🤖 Customer Support FAQ Bot")
st.write("Ask me anything related to customer support!")

user_input = st.text_input("🔎 Your Question:")

if st.button("Get Answer"):
    if user_input.strip() == "":
        st.warning("Please enter a question!")
    else:
        with st.spinner('Searching for the best answer...'):
            answer = get_best_answer(user_input)
            st.success("✅ Answer found!")
            st.markdown(f"### Answer:\n{answer}")

st.markdown("---")
st.caption("Powered by Streamlit, HuggingFace Datasets & RapidFuzz 🔥")